apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harness-poc
spec:
  defaultBackend:
    service:
      name: harness-poc
      port:
        number: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: harness-poc
  labels:
    app: harness-poc
    service: harness-poc
spec:
  ports:
  - port: 5001
    name: http
  selector:
    app: harness-poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-poc
  labels:
    app: harness-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harness-poc
  template:
    metadata:
      labels:
        app: harness-poc
    spec:
      containers:
      - name: harness-poc
        image: aramesh94/ciquickstart:23
        ports:
        - containerPort: 80

